language: node_js
node_js:
  - "4"
env:
  - DEBUG=beerTracker:*
  - APP_SECRET=tonttellanyone
  - PORT=3000
  - MONGOD_URI=mongodb://127.0.0.1/beerTracker
services:
  - mongo
before_script:
  - sleep 15
