language: node_js
node_js:
  - "4"
sudo: required
env:
  - DEBUG=beerTracker:*
  - APP_SECRET=tonttellanyone
  - PORT=3000
  - MONGOD_URI=mongodb://127.0.0.1/beerTracker
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
services:
  - mongodb
before_script:
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
