language: node_js
node_js:
  - "lts/*"
sudo: required
env:
  - DEBUG=beerTracker:*
  - PORT=3000
  - CXX=g++-4.8
  - NODE_ENV=dev
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - echo $FIREBASE_SERVICE_KEY_DEV | base64 --decode > $PWD/beer-tracker-db-key-dev.json
  - echo $FIREBASE_SERVICE_KEY | base64 --decode > $PWD/beer-tracker-db-key.json