language: node_js
sudo: required
node_js:
  - "4"
env:
  - DEBUG=beerTracker:*
  - APP_SECRET=tonttellanyone
  - PORT=3000
  - MONGOD_URI=mongodb://127.0.0.1/beerTracker
services:
  - mongod
before_script:
  - sleep 15
